include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
    - '**/*.gr.dart'
linter:
  rules:
    avoid_classes_with_only_static_members: false