name: noto_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  masonry_grid: ^1.0.0
  built_value: ^8.1.3
  built_collection: ^5.1.1
  uuid: ^3.0.5
  intl: ^0.17.0
  auto_route: ^3.2.0
  cloud_firestore: ^3.1.5
  firebase_core: ^1.10.6
  injectable: ^1.5.0
  get_it: ^7.2.0
  provider: ^6.0.1
  rxdart: ^0.27.3
  logger: ^1.1.0
  flutter_hooks: ^0.18.1
  functional_widget: ^0.9.2
  connectivity_plus: ^2.1.0
  cached_network_image: ^3.2.0
  mockito: ^5.0.17
  freezed_annotation: ^1.1.0
  google_fonts: ^2.1.1
  shared_preferences: ^2.0.11
  firebase_auth: ^3.3.4

dev_dependencies:
  lint: ^1.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  built_value_generator: ^8.1.3
  auto_route_generator: ^3.2.0
  injectable_generator: ^1.5.2
  dart_code_metrics: ^4.8.1
  functional_widget_annotation: ^0.9.2
  freezed: ^1.1.0

flutter:

  uses-material-design: true

  fonts:
      - family: MontserratAlternates
        fonts:
          - asset: fonts/MontserratAlternates-Medium.ttf
          - asset: fonts/MontserratAlternates-Italic.ttf
            style: italic